services:
    ollama:
        image: ollama/ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama_models:/root/.ollama

    mariadb:
        image: mariadb:11.7.2-ubi9
        container_name: mariadb-turing
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: turing_game
            MYSQL_USER: user 
            MYSQL_PASSWORD: pwd
        ports:
            - "3307:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql:Z
            - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        # healthcheck:
        #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
        #   interval: 10s
        #   timeout: 5s
        #   retries: 5

    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8003:8003"
        environment:
            - PYTHONUNBUFFERED=1  # altrimenti le print in websocoket.py e backned.py non vengono mostrate nel terminale
        depends_on:
            - mariadb
            - ollama
            # condition: service_healthy

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "8001:8001"
        depends_on:
            - backend
            # condition: service_started
    
# Monta il volume Docker esistente chiamato ollama dentro il container nel percorso /root/.ollama (come specificato sopra nei volumes del servizio)
volumes:
    ollama_models:
        external: true
        name: ollama 