# Docker Compose file per orchestrare i servizi: Ollama, MariaDB, Backend e Frontend
services:
    ollama:
        image: ollama/ollama:latest
        ports:
            - "11434:11434"
        volumes:
            - ./ollama_data:/root/.ollama   # dati Ollama dentro la cartella progetto

    mariadb:
        image: mariadb:11.7.2-ubi9
        container_name: mariadb-turing
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: turing_game
            MYSQL_USER: user 
            MYSQL_PASSWORD: pwd
        ports:
            - "3307:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql   # dati MariaDB dentro la cartella progetto
            - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8003:8003"
        environment:
            - PYTHONUNBUFFERED=1  # altrimenti le print in websocket.py e backend.py non vengono mostrate nel terminale
        depends_on:
            - mariadb
            - ollama

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "8001:8001"
        depends_on:
            - backend

